services:
  postgres:
    container_name: portfolio_db
    image: postgres:latest
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
       - ./portfolio_db/postgres-data:/var/lib/postgresql/data
    # networks:
    #   - db_network

  pgadmin:
    container_name: portfolio_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "${PGADMIN_PORT}:80"
    restart: always
    # networks:
    #   - db_network

  shali_be:
    image: portfolio_be:1.0
    container_name: portfolio_be
    build: ./backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:7000"
    volumes:
      - ./backend/src:/portfolio/src

# networks:
#   db_network:
