networks:
  network:
    driver: bridge

services:
  portfolio_postgres:
    container_name: portfolio_db
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${PORTFOLIO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PORTFOLIO_POSTGRES_PASSWORD}
      - POSTGRES_DB=${PORTFOLIO_POSTGRES_DB}
      - POSTGRES_SERVER=${PORTFOLIO_POSTGRES_SERVER}
      - POSTGRES_PORT=${PORTFOLIO_POSTGRES_PORT}
    ports:
      - "${PORTFOLIO_POSTGRES_PORT}:5432"
    restart: unless-stopped
    volumes:
      - ./portfolio_db/postgres-data:/var/lib/postgresql/data
    networks:
      - network

  portfolio_pgadmin:
    container_name: portfolio_pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PORTFOLIO_PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PORTFOLIO_PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PORTFOLIO_PGADMIN_PORT}:80"
    restart: unless-stopped
    networks:
      - network

  portfolio_be:
    image: portfolio_be:1.0
    container_name: portfolio_be
    build: ./backend
    restart: unless-stopped
    depends_on:
      - portfolio_postgres
    env_file:
      - ./.env
    ports:
      - ${PORTFOLIO_BACKEND_PORT}:7000
    volumes:
      - ./backend/src:/portfolio/src
    networks:
      - network
